### ISSUE TITLE
MySql Database and ARM chipsets

### ISSUE THREAD

**Issue by Brennan-J6** [toni-moreno/toni-moreno#3]
I have pulled down your application, in your notes you say to edit the config.toml in the location of  /etc/snmpcollector/config.toml. I am running your app on windows, pulled the code down using.

docker run -d --name=snmpcol_instance00 -p 80:8090 -v /mylocal/conf:/opt/snmpcollector/conf -v /mylocal/log:/opt/snmpcollector/log  tonimoreno/snmpcollector

i have setup an influxdb bucket. 

but i am wondering how do i make this point to the mysql database if the file is local to the container everytime a restart occurs will this not overwrite the config? 

Is it also possible for your app to run on ARM based chips or is there some dependencies that wont run on ARM chipsets?

**Comment by toni-moreno** [comment]
Please use the snmpcollector repo issue tracker to report any  problem you have with snmpcollector tool.
